-- 질문게시판 생성
CREATE QABOARD
( NUM 		NUMBER
, SUBJECT 	VARCHAR2(30) 
, CONTENT	VARCHAR2(1000)
, NICKNAME 	VARCHAR2(5)
, FILEPATH	VARCHAR2(20)
, CREATED	VARCHAR2(10)
, HITCOUNT	NUMBER
);

-- 글번호 시퀀스 생성
CREATE SEQENCE NUMSEQ
START WITH 0
MINVALUE 0
;


-- 조회수 증가
UPDATE QABOARD
SET HITCOUNT = HITCOUNT+1
WHERE NUM = ?