SELECT USER
FROM DUAL;
-->>SCOTT

DROP TABLE TBL_MEMBERLIST;
-->>Table TBL_MEMBERLIST이(가) 삭제되었습니다.

CREATE TABLE TBL_MEMBERLIST
( MID       NUMBER
, NAME      VARCHAR2(30)
, TELEPHONE VARCHAR2(40) 
, CONSTRAINT MEMBERLIST_MID_PK PRIMARY KEY(MID)
);
-->> Table TBL_MEMBERLIST이(가) 생성되었습니다.

DROP SEQUENCE MEMBERLISTSEQ;
-->> Sequence MEMBERLISTSEQ이(가) 삭제되었습니다.

CREATE SEQUENCE MEMBERLISTSEQ;
-->> Sequence MEMBERLISTSEQ이(가) 생성되었습니다.

--○ 데이터 입력
INSERT INTO TBL_MEMBERLIST(MID, NAME, TELEPHONE) 
VALUES (MEMBERLISTSEQ.NEXTVAL, '최은상', '010-8888-8888')
; 
INSERT INTO TBL_MEMBERLIST(MID, NAME, TELEPHONE) VALUES (MEMBERLISTSEQ.NEXTVAL, '한승원', '010-7777-7777')
;

COMMIT;

--○ 인원수 확인
SELECT COUNT(*) AS COUNT
FROM TBL_MEMBERLIST;

--○ 데이터 조회 
SELECT MID, NAME, TELEPHONE
FROM TBL_MEMBERLIST
ORDER BY MID;

--○ 데이터 삭제
DELETE
FROM TBL_MEMBERLIST
WHERE MID= 4;

--○ 데이터 수정
UPDATE TBL_MEMBERLIST
SET NAME='최은상', TELEPHONE='010-9999-0909'
WHERE MID=15;

COMMIT;